[package]
name = "rust_clear_target"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
crossterm = "0.29.0"
dirs = "6.0.0"
ratatui = "0.29.0"
serde = { version = "1.0.217", features = ["derive"] }
walkdir = "2.5.0"
toml = "0.8.19"
